# POST https://n8npanel.surb.com.br/webhook-test/personal-assistant
POST https://n8nwebhook.surb.com.br/webhook/personal-assistant
Content-Type: application/json

{
  "chatId": "12345689",
  "messgem": "Você trabalha com desenvolvimento de software para mobile?"
} 
